# Site settings
title: TRASE Lab at the University of Hong Kong
lab_name: TRASE Lab
author: >
  Prof. Sherry Chan and the TRASE Lab
institution: HKU
email: kwsherry@hku.hk
description: >
  TRASE Lab is a research team led by Professor Sherry Chan Kit Wa at the Department of Psychiatry, Li Ka Shing Faculty of Medicine, the University of Hong Kong. Our research directions revolve around schizophrenia and psychiatry, including early intervention service, longitudinal outcomes of psychosis, neurobiological basis of psychosis, treatment resistant schizophrenia, and social cognition.

 
url: "https://traselab.github.io"
baseurl: "/traselab"
twitter_username: /
github_username:  /
images_dir: "/images/"
team_photo: "/images/team/teampic.jpg"

navigation:
  - title: Projects
    url: /projects/
  - title: Team
    url: /team-static/
  - title: Publications
    url: /publications-static/
  - title: TripCal
    url: /tripcal/


# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
