# Site settings
title: TRASE Lab at the University of Hong Kong
lab_name: TRASE Lab
author: >
  Prof. Sherry Chan and the TRASE Lab
institution: HKU
email: kwsherry@hku.hk
description: >
  The TRASE Lab focuses on treatment-resistant schizophrenia recovery and social cognition in patients with psychotic disorders. 
baseurl: ""
url: "https://morinlab.github.io"
twitter_username: morinryan
github_username:  morinlab
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
