# Site settings
title: TRASE Lab at the University of Hong Kong
lab_name: TRASE Lab
author: >
  Prof. Sherry Chan and the TRASE Lab
institution: HKU
email: kwsherry@hku.hk
description: >
  TRASE Lab at the University of Hong Kong aims to examine the following topics: the evaluation of early intervention service, longitudinal outcomes of psychosis, treatment resistant schizophrenia, psychopathology (particularly insight and delusion) and its neurobiological basis, metacognition and insight, and also psychotic-like experience.
 
url: "https://traselab.github.io"
baseurl: "/traselab"
twitter_username: morinryan
github_username:  morinlab
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
